# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fdfa56ba02858b1b9bf61d2cc2efb96db24beb45a6fbb417d1ccec7f65edc32b34417dc52c8a8b57a1e1ce0bc9012d532a7995c843e2817070239cfe77bdcfe

test:
  secret_key_base: 3b31cae051c2afa1dd81d799600e636e2fda3c6b602712e6769f4784354e6f15a6919e1629ce3a3fd14989b4a678a34c4fe3f53a8a679380f8f26c32171f76a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
